apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "newegg-nginx.full_name" . }}
  labels: 
    {{- include "newegg-nginx.release_labels" . | indent 4 }}
spec:
  replicas: {{ default 1 .Values.Replicas }}
  template:
    metadata:
      labels:
        {{- include "newegg-nginx.release_labels" . | indent 8 }}
    spec:
      containers:
        - name: newegg-nginx
          image: "{{.Values.Image}}:{{.Values.ImageTag}}"
          imagePullPolicy: "{{.Values.ImagePullPolicy}}"
          ports:
            - containerPort: {{.Values.ContainerPort}}
              protocol: TCP
          resources:
            requests:
              cpu: "{{.Values.Cpu}}"
              memory: "{{.Values.Memory}}"
