apiVersion: v1
kind: Service
metadata:
  name: {{ template "newegg-nginx.full_name" . }}
  labels: 
    {{- include "newegg-nginx.release_labels" . | indent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.ServiceType | quote }}
  ports:
  - port: {{.Values.ServicePort}}
    targetPort: {{.Values.ContainerPort}}
    protocol: TCP
  selector:
    app: {{ template "newegg-nginx.full_name" . }}
